name: Github Release

on:
  push:
    branches: [ master ]

jobs:
  create-release:
    name: Create Release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Setup git
        run: |
          git config user.email "developers@messagebird.com"
          git config user.name "MessageBird CI"
      - name: Prepare description
        run: |
          awk '/^## / { if (p) { exit }; { p=1; next } } p && NF' CHANGELOG.md > CHANGELOG.tmp
      - name: Prepare tag
        run: |
          export TAG=$(awk '/^## / {print $2}' CHANGELOG.md)
          echo "TAG=$TAG" >> $GITHUB_ENV
      - name: Create Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ env.TAG }}
          release_name: Version ${{ env.TAG }}
          body_path: CHANGELOG.tmp
          draft: false
          prerelease: false
